#!/usr/bin/ruby

#apt_load_options = "--no-download"
apt_load_options = ""


def exc(cmd)
  puts cmd
  `#{cmd}`
  exit $?.exitstatus if $?.exitstatus != 0
end

exc "apt-get -y #{apt_load_options} install libxml2-dev libxslt1-dev"
exc "gem1.8 install nokogiri"
exc "gem1.8 install rspec rspec-rails webrat cucumber"
exc "gem1.8 install rubyforge technicalpickles-jeweler ZenTest"


puts "If you want autotest to execute Cucumber tests, remember to add 'export AUTOFEATURE=\"true autospec\"' to the bottom of your .bashrc file (or the equivalent for your shell)."
puts "Don't forget to run 'rake db:schema:load' prior to starting development."

