#!/usr/bin/ruby


#apt_load_options = "--no-download"
apt_load_options = ""

def exc(cmd)
  puts cmd
  `#{cmd}`
end


          # get rid of the gem-installed version of WontoMedia, so
          # we don't bump into it running from our Git repository
exc "gem1.8 uninstall wontomedia"

          # need to install Git so we can use it to install WontoMedia
exc "apt-get -y #{apt_load_options} install git-core"
exit $?.exitstatus if $?.exitstatus != 0
