# !!!!! This file was auto-generated by "script/generate cucumber"  IF
# !!!!! YOU MODIFY IT, you *MUST* replace this notice with a WontoMedia
# !!!!! copyright attribute (get from policy/copyright-notices/header.rb) 
# !!!!! *AND* remove the name of this file from the copyright checking
# !!!!! ignore list (policy/copyright-notice-ignore) *BEFORE*
# !!!!! submitting to any version control that feeds back to the
# !!!!! WontoMedia project.


# Sets up the Rails environment for Cucumber
ENV["RAILS_ENV"] = "test"
$KCODE = "u"
require File.expand_path(File.dirname(__FILE__) + '/../../config/environment')
require 'cucumber/rails/world'
require 'cucumber/formatters/unicode' # Comment out this line if you don't want Cucumber Unicode support
Cucumber::Rails.use_transactional_fixtures

require 'webrat'
Webrat.configure do |config|
  config.mode = :rails
end

require 'cucumber/rails/rspec'
