# !!!!! This file was auto-generated by "capify" IF YOU MODIFY IT, you
# !!!!! *MUST* replace this notice with a WontoMedia copyright
# !!!!! attribute (get from policy/copyright-notices/header.rb) *AND*
# !!!!! remove the name of this file from the copyright checking
# !!!!! ignore list (policy/copyright-notice-exceptions) *BEFORE*
# !!!!! submitting to any version control that feeds back to the
# !!!!! WontoMedia project.



load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }

load 'config/deploy' # remove this line to skip loading any of the default tasks