# !!!!! This file was auto-generated by "ruby rails wontomedia"  IF
# !!!!! YOU MODIFY IT, you *MUST* replace this notice with a WontoMedia
# !!!!! copyright attribute (get from policy/copyright-notices/header.rb) 
# !!!!! *AND* remove the name of this file from the copyright checking
# !!!!! ignore list (policy/copyright-notice-ignore) *BEFORE*
# !!!!! submitting to any version control that feeds back to the
# !!!!! WontoMedia project.


# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
# Mime::Type.register_alias "text/html", :iphone
